### ISSUE TITLE
Firefox asks to store any password entered into lockbox

### ISSUE THREAD

**Issue by franziskuskiefer** [mozilla-lockbox/lockbox-extension#230] opened 2017-10-23 09:19 UTC
Entering anything into lockbox produces a Firefox door hanger asking me whether I want to store the login.

![lockbox-store](https://user-images.githubusercontent.com/890105/31881455-d7358be2-b7e3-11e7-923e-27d8cb21e8b4.png)

**Comment by linuxwolf** [comment] 2017-10-23 15:36
duplicate of #184

**Closed** 2017-10-23 15:37 UTC
