### ISSUE TITLE
Test plan for Telemetry

### ISSUE THREAD

**Issue by devinreams** [mozilla-lockbox/lockbox-extension#353] opened 2017-11-28 16:59 UTC
Ideally, some day we'd like to have some automated integration tests that confirm our Telemetry events are (still) working as expected. Currently, if we refactor or change some big features, we may miss the fact an event was moved or removed unexpectedly.

@mbrandt we spoke briefly about this, and after chatting with @irrationalagent, we wanted to put a placeholder here to discuss both long and short term options for confirming our Telemetry events are working as expected.

- Is a good short term approach to add a test rail (manual) test plan to perform some actions and confirm the events are logged as expected?

- Is a good long term approach to piggy-back on the Selenium / integration test work in progress to programmatically confirm Telemetry events are recorded in the browser?

Either way, @irrationalagent and I discussed potentially re-using the metrics.md as the foundation for a "test plan" to confirm there are no regressions after a big feature like the doorhanger by @jimporter lands #338.

**Comment by m8ttyB** [comment] 2017-11-28 18:13
From a test automation perspective, I've not looked into how this might be solved, @jrbenny35 do you have familiarity in this area? Ideally automating this on some level would be preferred. Previous products have taken a fail-forwards approach.

**Comment by jrbenny35** [comment] 2017-11-28 19:54
I did some manual testing with telemetry but I have not touched it in a while.

It could be automated using the integration tests, or a suite similar, but my thing is that I don't know how to check the pings. Of course I can ask around and see how it's done currently.

**Comment by m8ttyB** [comment] 2017-11-28 20:00
Thx @jrbenny35. I'm definetly interested in learning from you. @devinreams truthfully I'm not a 100% sure this should be included in the regression test suites that get run on a routine basis, manual or otherwise. We'll grok on it for bit and do some due diligence.

**Comment by jimporter** [comment] 2017-12-14 06:15
@m8ttyB With #405 (which I'd like to get to real soon), should we close this in favor of that one? I really want automated tests because the middleware has 0 coverage right now, which means we no longer know automatically if something causes our telemetry to catastrophically break our Redux backend (e.g. by throwing an exception and failing to dispatch our Redux actions).

**Comment by sandysage** [comment] 2017-12-20 16:31
I've changed the title of this issue to better encompass: we need a test plan for telemetry.

@m8ttyB Does it make sense to start with a manual test plan?

It looks like #405 is part of automating telemetry testing, but am I correct in assuming it's not the full scope? Can we chip away at this with issues like #405 to continue to work towards full automation for telemetry testing?

**Comment by m8ttyB** [comment] 2017-12-20 17:32
@sandysage I have a meeting between @irrationalagent, @jimporter, and myself tagged for early January 2018 to scope what's needed. Currently we're relying on @irrationalagent's test plan to verify that the telemetry hooks perform as expected. I agree, work on issue #405 should continue in earnest.

I'm still of the opinion that the automation efforts should not be part the integration work that @jrbenny35 helped us standup. Integrating these checks into lower level tests, not e2e makes more sense to me.

**Comment by m8ttyB** [comment] 2018-01-09 15:36
A meeting w/ Jim and Leif is set for Monday, January 15th.

**Comment by m8ttyB** [comment] 2018-01-10 16:09
I made a mistake, January 15th is MLK day. I also may have some unexpected PTO required next week. I moved the meeting to January 22.

**Comment by m8ttyB** [comment] 2018-01-23 00:15
@jimporter, @irrationalagent, and I met today and drafted an initial telemetry test plan. Note, this still being drafted and can be viewed here https://docs.google.com/document/d/1Mlew7-KPuWBt-nz5pj7ZwRsGuUnmg7V_JbLhUOUC2CI/edit?usp=sharing

**Comment by m8ttyB** [comment] 2018-01-24 18:19
The document has been finalized, to close this I'll work with @irrationalagent to find the correct home for the test plan.

**Closed** 2018-01-24 21:57 UTC
Labels: chore, in progress
