### ISSUE TITLE
Signing in with a different user errors out silently

### ISSUE THREAD

**Issue by rfk** [mozilla-lockbox/lockbox-extension#577] opened 2018-02-27 02:20 UTC
STR:

* Sign in to Lockbox with your Firefox Account, e.g. user1@example.com
* Quit Firefox and restart
* Sign in to Lockbox again, but on the FxA signin form, click "use a different account" and sign in as a different user, e.g. user2@example.com
* Complete the FxA signin process

Expected result:

* I'm signed in to Lockbox as user2@example.com
* Or alternately, I get some sort of error/warning that I'm doing something crazy

Actual result:

* The OAuth popup closes, appearing to have succeeded
* Lockbox remains locked, with the toolbar icon in the "closed" state
* Clicking the toolbar icon presents me with the "sign in" button
* Clicking the "sign in" button does nothing; it does not re-launch the OAuth popup

**Comment by m8ttyB** [comment] 2018-02-27 15:17
@rfk this one caught me off guard recently as well. It's long running and known bug. Closing as a duplicate of issue #394.

**Closed by m8ttyB** 2018-02-27 15:17 UTC
