### ISSUE TITLE
sync passwords on different devices with same master password

### ISSUE THREAD

**Issue by mu22le** [mozilla-lockbox/lockbox-extension#271] opened 2017-10-31 10:40 UTC
It would be useful is being able to sync your passwords on different devices while using a master password. With the current firefox password manager, you have to select one feature or the other.

**Comment by devinreams** [comment] 2017-11-02 16:43
We definitely agree! We're ultimately working towards a cross-platform solution that doesn't have the same barriers you might be familiar with using other similar products today.

The groundwork for this development is being described and organized at #209 

I'm going to close this as  as this is very much on our roadmap. Thanks for your input!

---
Duplicate of #209

**Comment by devinreams** [comment] 2017-11-02 16:44
Duplicate of #209

**Closed by devinreams** 2017-11-02 16:43 UTC
Labels: closed-duplicate
