### ISSUE TITLE
Cannot install in 57 beta

### ISSUE THREAD

**Issue by sandysage** [mozilla-lockbox/lockbox-extension#188] opened 2017-10-17 12:02 UTC
> I cannot install this in 57 beta, and get this warning from Firefox that it won't allow it to be installed: https://i.imgur.com/wd3ttON.png

**Comment by linuxwolf** [comment] 2017-10-17 15:40
This looks like a duplicate of #189 .

**Closed** 2017-10-17 16:22 UTC
