### ISSUE TITLE
Password Generation

### ISSUE THREAD

**Issue by TanviHacks** [mozilla-lockbox/lockbox-extension#161] opened 2017-10-11 18:51 UTC
One of the big pieces that is missing from Firefox's password manager that would help protect users from password reuse is password generation.  Would it be possible to add password generation the alpha product?  Thanks!

**Comment by sandysage** [comment] 2017-10-11 19:21
It's one of the areas we're exploring with more user research and UX prototypes; around the larger area of password habits. Our goal is to better understand how users can/will adopt password generation, knowing that are users have largely misinformed views about privacy and security.

We expect to have more insights over the next couple of months. Based on the findings, we'll be able to introduce the functionality in our Beta offering.

I'll post updates here in this issue as we learn more and start scoping the work for implementation.

**Comment by devinreams** [comment] 2018-03-26 22:14
Duplicate of #286

**Closed by devinreams** 2018-03-26 22:14 UTC
Labels: closed-duplicate, feature
