### ISSUE TITLE
Firefox 56, failured telemetry ping preventing 1st run of extension

### ISSUE THREAD

**Issue by m8ttyB** [mozilla-lockbox/lockbox-extension#182] opened 2017-10-16 20:59 UTC
Installation of Lockbox extension via [testpilot latest](https://testpilot.firefox.com/files/lockbox@mozilla.com/latest) appears to work, however clicking the Lockbox toolbar icon fails silently (for the user) and produces the following traceback.

Firefox 56 only, OSX and Window 10.

<img width="896" alt="screen shot 2017-10-16 at 2 33 00 pm" src="https://user-images.githubusercontent.com/63193/31635045-bb7a662c-b282-11e7-8c6c-de6af95bcfc8.png">

**Comment by jimporter** [comment] 2017-10-16 21:19
I don't see any errors from our code in here (aside from a Redux warning that I can't reproduce).

**Comment by sandysage** [comment] 2017-10-20 20:17
Evaluate the issue further. Based on findings make a determination if  a) we address it, b) set the baseline to 57 or c) do nothing (always an option)

**Comment by jimporter** [comment] 2017-10-23 05:28
I tried this again. I vaguely recall this not working when I tested it, but it works just fine now using the link in the first comment. It also works fine if I use unbranded Firefox and run a local build of the add-on. I think we can probably close this.

**Comment by linuxwolf** [comment] 2017-10-25 23:01
closed as unreproducible

**Closed by linuxwolf** 2017-10-25 23:01 UTC
Labels: bug, to do
